version: "3.7"

services: 

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:80
    volumes: 
      - ./wp-content:/var/www/html/wp-content  
    environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpressdb
    networks:
      - wordpress-net   
   
  db:
    image: mysql:5.7
    container_name: wordpressdb
    restart: always
    volumes: 
      - db_data:/var/lib/mysql
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: '1'
        MYSQL_DATABASE: wordpressdb
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
    networks:
      - wordpress-net

networks: 
  wordpress-net:

volumes: 
  db_data:
