version: "3.7"

services: 

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpressdb
   
  db:
    image: mysql:5.7 
    restart: always
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: '1'
        MYSQL_DATABASE: wordpressdb
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
